receivers:
  otlp:
    protocols:
      http:
        cors_allowed_origins:
          - http://*
          - https://*

exporters:
  elastic:
    apm_server_url: "http://apm-server:8200"
    secret_token: ""
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - elastic
        - zipkin
        - jaeger
      processors:
        - batch
