receivers:
  zipkin:
  otlp:
    protocols:
      http:
        cors_allowed_origins:
        - http://*
        - https://*

exporters:
  elastic:
    apm_server_url: 'https://93240c290a9c46d390e5cc7a6dcae9cb.apm.us-west1.gcp.cloud.es.io:443' 
    secret_token: 'gwguK5uBRB927mgY2q'
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: 
        - zipkin
        - otlp
      exporters:
        - elastic
        - zipkin
        - jaeger
      processors:
        - batch
