version: "3"

services:
  nodejs-opentelemetry-master:
    container_name: nodejs-opentelemetry-master
    build:
      context: ./nodejs-opentelemetry-master
      dockerfile: Dockerfile
    image: nodejs-opentelemetry-master
    command: "npm run start:debug"
    volumes:
      - ./nodejs-opentelemetry-master:/app
    ports:
      - 3000:3000
    tty: true
    networks:
      - custom_network

  nodejs-opentelemetry-web:
    container_name: nodejs-opentelemetry-web
    build:
      context: ./nodejs-opentelemetry-web
      dockerfile: Dockerfile
    image: nodejs-opentelemetry-web
    ports:
      - 8090:8090
    tty: true
    networks:
      - custom_network

  nodejs-opentelemetry-slave:
    container_name: nodejs-opentelemetry-slave
    build:
      context: ./nodejs-opentelemetry-slave
      dockerfile: Dockerfile
    image: nodejs-opentelemetry-slave
    command: "npm run start:debug"
    volumes:
      - ./nodejs-opentelemetry-slave:/app
    ports:
      - 3001:3001
    tty: true
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: payvision
